const events = {
  setNickname: 'setNickname',
  newUser: 'newUser',
  disconnect: 'disconnect',
  disconnected: 'disconnected',
  sendMsg: 'sendMsg',
  newMsg: 'newMsg',
  beginPath: 'beginPath',
  strokePath: 'strokePath',
  beganPath: 'beganPath',
  strokedPath: 'strokedPath',
  fillClear: 'fillClear',
  fillCleared: 'fillCleared',
  fill: 'fill',
  filled: 'filled',
  playerUpdated: 'playerUpdated',
  startGame: 'startGame',
  endGame: 'endGame',
  painterNotif: 'painterNotif',
  clearGameNotif: 'clearGameNotif',
  noPerson: 'noPerson',
  correctAnswer: 'correctAnswer',
  startTimeout: 'startTimeout',
  timeEnded: 'timeEnded',
};

export default events;
